#!/bin/sh

cat repo | sudo tee -a /etc/pacman.conf

sudo pacman --noconfirm -Syu

echo "###########################"
echo "## Downloading pkgs.txt. ##"
echo "###########################"
sudo sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
sudo pacman --needed --ask 4 -Sy -< pkgs

echo "#########################################################"
echo "## Installing Doom Emacs. This may take a few minutes. ##"
echo "#########################################################"
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom env
~/.emacs.d/bin/doom -y install
~/.emacs.d/bin/doom sync
